package com.healthmate.ai.service;

import com.healthmate.ai.dto.ReminderRequest;
import com.healthmate.ai.entity.Reminder;
import com.healthmate.ai.model.Medication;
import com.healthmate.ai.model.MedicineExplanation;
import com.healthmate.ai.repository.ReminderRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

/**
 * Agent 4: Prescription Reminder.
 * Explains a medicine using the LLM, cross-checked against a curated local medication
 * reference for reliability, and manages simple in-app reminder scheduling.
 * IMPORTANT: no real push/SMS/email notifications are ever sent — reminders are purely
 * an in-app, user-checked list.
 */
@Service
public class ReminderService {

    private final ReminderRepository reminderRepository;
    private final MedicationDbService medicationDbService;
    private final GroqService groqService;

    public ReminderService(ReminderRepository reminderRepository,
                            MedicationDbService medicationDbService,
                            GroqService groqService) {
        this.reminderRepository = reminderRepository;
        this.medicationDbService = medicationDbService;
        this.groqService = groqService;
    }

    public MedicineExplanation explainMedicine(String medicineName) {
        MedicineExplanation explanation = new MedicineExplanation();
        explanation.setMedicineName(medicineName);

        Optional<Medication> localMatch = medicationDbService.findByName(medicineName);
        explanation.setFoundInLocalDb(localMatch.isPresent());

        String prompt;
        if (localMatch.isPresent()) {
            Medication m = localMatch.get();
            explanation.setLocalDbNote("Cross-checked against HealthMate's local medication reference database.");
            prompt = String.format(
                    "Explain the medicine '%s' in plain, friendly language for a patient (5-6 sentences, specific and "
                    + "concrete rather than generic filler): what it's specifically used for, why timing/food matter for "
                    + "THIS particular medicine (not generic advice), and one specific, non-obvious safety consideration "
                    + "relevant to this medicine in particular. "
                    + "For reference, our local database describes it as: category '%s', common use '%s', "
                            + "typical frequency '%s', notes '%s'. Keep your explanation consistent with this reference and "
                            + "weave those specifics naturally into your explanation rather than just restating them. "
                            + "Do not give a specific dosage prescription — only general informational guidance, and "
                            + "remind the patient to follow their doctor's or pharmacist's specific instructions.",
                    medicineName, m.getCategory(), m.getCommonUse(), m.getTypicalFrequency(), m.getNotes()
            );
        } else {
            explanation.setLocalDbNote(
                    "This medicine was not found in HealthMate's local reference database, so this explanation is "
                            + "generated by AI alone and has not been cross-checked locally — please verify with your pharmacist.");
            prompt = String.format(
                    "Explain the medicine '%s' in plain, friendly language for a patient (5-6 sentences, specific and "
                    + "concrete rather than generic filler): what it's specifically used for, why timing/food matter for "
                    + "THIS particular medicine, and one specific, non-obvious safety consideration relevant to it. "
                            + "Do not give a specific dosage prescription — only general informational guidance, and "
                            + "remind the patient to follow their doctor's or pharmacist's specific instructions.",
                    medicineName
            );
        }

        explanation.setExplanation(groqService.singlePrompt(
                "You are an informational medicine explainer. You never prescribe dosages or replace a pharmacist's "
                        + "or doctor's guidance. Give specific, concrete, medicine-particular information rather than "
                        + "generic advice that could apply to any drug — avoid filler phrases like 'as with any medication'.",
                prompt
        ));

        return explanation;
    }

    public Reminder createReminder(ReminderRequest request) {
        Reminder reminder = new Reminder();
        reminder.setMedicineName(request.getMedicineName());
        reminder.setReminderTime(request.getReminderTime());
        reminder.setFrequency(request.getFrequency());
        reminder.setDosageNote(request.getDosageNote());
        reminder.setTakenToday(false);
        return reminderRepository.save(reminder);
    }

    public List<Reminder> listAll() {
        return reminderRepository.findAllByOrderByReminderTimeAsc();
    }

    public void markTaken(Long id) {
        reminderRepository.findById(id).ifPresent(r -> {
            r.setTakenToday(true);
            reminderRepository.save(r);
        });
    }

    public void resetTaken(Long id) {
        reminderRepository.findById(id).ifPresent(r -> {
            r.setTakenToday(false);
            reminderRepository.save(r);
        });
    }

    public void remove(Long id) {
        reminderRepository.deleteById(id);
    }

    public long countActive() {
        return reminderRepository.countByTakenTodayFalse();
    }

    public List<Medication> allMedications() {
        return medicationDbService.getAllMedications();
    }
}
